# Generated by Django 2.0 on 2017-12-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trek',
            name='duration',
            field=models.DurationField(max_length=100),
        ),
    ]
