# Generated by Django 2.0 on 2017-12-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_auto_20171222_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='file_link',
            field=models.CharField(default='google.com', max_length=250),
        ),
        migrations.AlterField(
            model_name='trek',
            name='duration',
            field=models.DurationField(),
        ),
    ]
