# Generated by Django 2.0 on 2017-12-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_auto_20171223_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='card_pic',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
